In [1]:
#Importing Libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
data = pd.read_csv("L1Data.csv")

In [3]:
data

Class   Age  Funds Sale
0    Freshmen  18.0  600.0   No
1    Freshmen  18.0  500.0   No
2    Freshmen  18.0  600.0   No
3      Senior  23.0  800.0   No
4      Junior  21.0  400.0  Yes
5    Freshmen  19.0  600.0   No
6    Freshmen  20.0  600.0   No
7      Senior  24.0    NaN  Yes
8   Sophomore  23.0  620.0  Yes
9   Sophomore  25.0  800.0  Yes
10     Junior  21.0  900.0   No
11     Junior  21.0  650.0  Yes
12  Sophomore   NaN  500.0   No
13     Junior  21.0  800.0   No
14     Junior  20.0  650.0  Yes
15  Sophomore  21.0  580.0  Yes
16  Sophomore  20.0  800.0  Yes
17     Senior  26.0    NaN  Yes
18     Senior  25.0    NaN  Yes
19     Senior  41.0    NaN  Yes
20  Sophomore   NaN  500.0   No
21   Freshmen  18.0  500.0   No
22   Freshmen  18.0  500.0   No
23   Freshmen  18.0  600.0   No

In [38]:
#without the .values at the end, data is imported with pandas, creating a "pretty" data table.  
#using .values saves the information in a raw format
x = data[["Class", "Age", "Funds"]].values


In [43]:
x

array([['Freshmen', 18.0, 600.0],
       ['Freshmen', 18.0, 500.0],
       ['Freshmen', 18.0, 600.0],
       ['Senior', 23.0, 800.0],
       ['Junior', 21.0, 400.0],
       ['Freshmen', 19.0, 600.0],
       ['Freshmen', 20.0, 600.0],
       ['Senior', 24.0, nan],
       ['Sophomore', 23.0, 620.0],
       ['Sophomore', 25.0, 800.0],
       ['Junior', 21.0, 900.0],
       ['Junior', 21.0, 650.0],
       ['Sophomore', nan, 500.0],
       ['Junior', 21.0, 800.0],
       ['Junior', 20.0, 650.0],
       ['Sophomore', 21.0, 580.0],
       ['Sophomore', 20.0, 800.0],
       ['Senior', 26.0, nan],
       ['Senior', 25.0, nan],
       ['Senior', 41.0, nan],
       ['Sophomore', nan, 500.0],
       ['Freshmen', 18.0, 500.0],
       ['Freshmen', 18.0, 500.0],
       ['Freshmen', 18.0, 600.0]], dtype=object)

In [6]:
y = data[["Sale"]].values

In [7]:
y

array([['No'],
       ['No'],
       ['No'],
       ['No'],
       ['Yes'],
       ['No'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['No'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['Yes'],
       ['Yes'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['No'],
       ['No'],
       ['No']], dtype=object)

In [44]:
x

array([['Freshmen', 18.0, 600.0],
       ['Freshmen', 18.0, 500.0],
       ['Freshmen', 18.0, 600.0],
       ['Senior', 23.0, 800.0],
       ['Junior', 21.0, 400.0],
       ['Freshmen', 19.0, 600.0],
       ['Freshmen', 20.0, 600.0],
       ['Senior', 24.0, nan],
       ['Sophomore', 23.0, 620.0],
       ['Sophomore', 25.0, 800.0],
       ['Junior', 21.0, 900.0],
       ['Junior', 21.0, 650.0],
       ['Sophomore', nan, 500.0],
       ['Junior', 21.0, 800.0],
       ['Junior', 20.0, 650.0],
       ['Sophomore', 21.0, 580.0],
       ['Sophomore', 20.0, 800.0],
       ['Senior', 26.0, nan],
       ['Senior', 25.0, nan],
       ['Senior', 41.0, nan],
       ['Sophomore', nan, 500.0],
       ['Freshmen', 18.0, 500.0],
       ['Freshmen', 18.0, 500.0],
       ['Freshmen', 18.0, 600.0]], dtype=object)

In [45]:
from sklearn.preprocessing import Imputer

In [46]:
#imputing the missing values...axis = 0 means by column
imputing_configuration = Imputer(missing_values = 'NaN', strategy = 'mean', axis = 0)

In [47]:
imputed_values = imputing_configuration.fit(x[:,[1,2]])

In [48]:
#this says to look at x, look at the column1 and column2 of x (age and funds), then replace
#the missing values with these imputed values
x[:,[1,2]] = imputed_values.transform(x[:,[1,2]])

In [50]:
x[7][2]

625.0

In [15]:
from sklearn.preprocessing import LabelEncoder

In [18]:
discreteCoder_x = LabelEncoder()

#replace the first column with the output of discreteCoder
#by using .fit_transform, we will encode the discrete column AND return the encoded labels
x[:,0] = discreteCoder_x.fit_transform(x[:,0])

In [19]:
x

array([[0, 18.0, 600.0],
       [0, 18.0, 500.0],
       [0, 18.0, 600.0],
       [2, 23.0, 800.0],
       [1, 21.0, 400.0],
       [0, 19.0, 600.0],
       [0, 20.0, 600.0],
       [2, 24.0, 625.0],
       [3, 23.0, 620.0],
       [3, 25.0, 800.0],
       [1, 21.0, 900.0],
       [1, 21.0, 650.0],
       [3, 21.772727272727273, 500.0],
       [1, 21.0, 800.0],
       [1, 20.0, 650.0],
       [3, 21.0, 580.0],
       [3, 20.0, 800.0],
       [2, 26.0, 625.0],
       [2, 25.0, 625.0],
       [2, 41.0, 625.0],
       [3, 21.772727272727273, 500.0],
       [0, 18.0, 500.0],
       [0, 18.0, 500.0],
       [0, 18.0, 600.0]], dtype=object)

In [20]:
from sklearn.preprocessing import OneHotEncoder

In [21]:
#the default for OneHotEncoder is to try and catergorize and pivot wider ALL the columns, 
#by specifiying column zero, we only want to apply it to the first column.

#we are creating a function using OneHotEncoder as a base to alter the first column in the entry
discreteCoder_x_dummies = OneHotEncoder(categorical_features = [0])
x = discreteCoder_x_dummies.fit_transform(x).toarray()

#the effect of this is to take a single column with categorical information, and create multiple columns
#that are all binary representations of the total number of categories in the categorical column data.
#in this case, there are four classes.  Now we have four columns, all binary.

In [22]:
x

array([[  1.        ,   0.        ,   0.        ,   0.        ,
         18.        , 600.        ],
       [  1.        ,   0.        ,   0.        ,   0.        ,
         18.        , 500.        ],
       [  1.        ,   0.        ,   0.        ,   0.        ,
         18.        , 600.        ],
       [  0.        ,   0.        ,   1.        ,   0.        ,
         23.        , 800.        ],
       [  0.        ,   1.        ,   0.        ,   0.        ,
         21.        , 400.        ],
       [  1.        ,   0.        ,   0.        ,   0.        ,
         19.        , 600.        ],
       [  1.        ,   0.        ,   0.        ,   0.        ,
         20.        , 600.        ],
       [  0.        ,   0.        ,   1.        ,   0.        ,
         24.        , 625.        ],
       [  0.        ,   0.        ,   0.        ,   1.        ,
         23.        , 620.        ],
       [  0.        ,   0.        ,   0.        ,   1.        ,
         25.        , 800. 

In [23]:
#this is going to change the categorical data for our outcome variable
#we have create a new encoder each time
#since the outcome variable has only two categories, we dont have to worry about the weights of
#the categories, so we can just leave them as 1s and 0s
discreteCoder_y = LabelEncoder()
y = discreteCoder_y.fit_transform(y)

/home/scott/anaconda3/envs/conda_ML/lib/python3.5/site-packages/sklearn/preprocessing/label.py:111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [24]:
y

array([0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0])

In [25]:
from sklearn.cross_validation import train_test_split

/home/scott/anaconda3/envs/conda_ML/lib/python3.5/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [27]:
#we are creating a split between the training and testing data

#train_test_split will set aside 20% of the data for testing, and we have set a seed at 1693 for replication 
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=1693)

In [31]:
y_train

array([1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1])

In [36]:
#feature scaling
from sklearn.preprocessing import StandardScaler

scale_x = StandardScaler()
x_train = scale_x.fit_transform(x_train)
x_test = scale_x.transform(x_test)

In [35]:
x_train

array([[-0.67936622,  1.93649167, -0.5976143 , -0.51639778, -0.24692088,
         0.14633175],
       [-0.67936622, -0.51639778,  1.67332005, -0.51639778,  0.7398184 ,
        -0.06429728],
       [ 1.47196014, -0.51639778, -0.5976143 , -0.51639778, -0.83896446,
        -1.11744247],
       [-0.67936622,  1.93649167, -0.5976143 , -0.51639778, -0.24692088,
        -1.95995861],
       [ 1.47196014, -0.51639778, -0.5976143 , -0.51639778, -0.44426874,
        -0.27492632],
       [-0.67936622, -0.51639778, -0.5976143 ,  1.93649167,  0.14777483,
        -0.10642309],
       [-0.67936622, -0.51639778, -0.5976143 ,  1.93649167,  0.54247055,
         1.41010597],
       [-0.67936622, -0.51639778,  1.67332005, -0.51639778,  3.70003627,
        -0.06429728],
       [-0.67936622, -0.51639778,  1.67332005, -0.51639778,  0.34512269,
        -0.06429728],
       [-0.67936622, -0.51639778,  1.67332005, -0.51639778,  0.54247055,
        -0.06429728],
       [ 1.47196014, -0.51639778, -0.5976143 , -0.

In [37]:
y_test

array([0, 1, 0, 0, 0])